name: Fetch Dataset

on:
  schedule:
    - cron: '0 0 * * 0'  # This runs at midnight every Sunday
  workflow_dispatch:  # Allows manual triggering from the GitHub Actions tab

jobs:
  fetch-dataset:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Jupyter
      run: |
        pip install jupyter

    - name: Run the notebook
      run: |
        jupyter nbconvert --to notebook --execute nlp-project.ipynb --output executed_notebook.ipynb
